name: Pushing DOcker Image to ECR with Github Actions

run-name: ${{ github.actor }} is pushing image to ECR

on:
  push:
    branches: ["INTERN-791", "main"]
  pull_request:
    branches: ["main"]

env:
  ECR_REPOSITORY: nodeimage
  IMAGE_TAG: ${{ github.sha }}
  DOCKERFILE_DIR: Node
  REGION: us-east-1

jobs:
  ECRpush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{env.REGION}}

      - name: Create ECR Repo if it doesn't exist
        id: ecr-create
        run: aws ecr describe-repositories --repository-names ${{env.ECR_REPOSITORY}} || aws ecr create-repository --repository-name=${{env.ECR_REPOSITORY}} --region=${{env.REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        working-directory: ${{env.DOCKERFILE_DIR}}
